"""Orchestration and refusal.

The four refusal tests are pure unit tests. Everything below them drives the
whole pipeline through two real subprocesses — a stand-in OpenSCAD that emits
STLs of a requested size, and a stand-in slicer that emits a real .gcode.3mf
— because the interesting failures here live at those two boundaries, and a
test that mocks them away proves only that the orchestration talks to itself.
"""

import json
import os
import struct
import sys
import zipfile
from pathlib import Path

import pytest

from cadloop import machine, pipeline, slicer_server


def test_run_refuses_without_a_machine(tmp_path, monkeypatch):
    monkeypatch.setenv("CADLOOP_MACHINE", str(tmp_path / "none.json"))
    src = tmp_path / "m.scad"
    src.write_text("cube(10);")
    r = pipeline.run("m.scad", tmp_path)
    assert r["ok"] is None
    assert "setup_printer" in r["reason"]


def test_run_refuses_a_stale_machine(tmp_path, monkeypatch):
    monkeypatch.setenv("CADLOOP_MACHINE", str(tmp_path / "rec.json"))
    machine.save({"schema": machine.SCHEMA, "name": "X",
                  "slicer": {"binary": "/nonexistent", "version": "1"},
                  "profiles": {}, "derived": {}, "fingerprint": {}})
    src = tmp_path / "m.scad"
    src.write_text("cube(10);")
    r = pipeline.run("m.scad", tmp_path)
    assert r["ok"] is None
    assert "stale" in r["reason"] or "no longer" in r["reason"]


def test_run_refuses_a_source_outside_the_workspace(tmp_path, monkeypatch):
    monkeypatch.setenv("CADLOOP_MACHINE", str(tmp_path / "none.json"))
    r = pipeline.run("../../etc/passwd", tmp_path)
    assert r["ok"] is None
    assert "workspace" in r["reason"]


def test_report_is_json_serialisable(tmp_path, monkeypatch):
    monkeypatch.setenv("CADLOOP_MACHINE", str(tmp_path / "none.json"))
    src = tmp_path / "m.scad"
    src.write_text("cube(10);")
    json.loads(json.dumps(pipeline.run("m.scad", tmp_path)))


# --------------------------------------------------------------------
# stand-in binaries
# --------------------------------------------------------------------

# Reads -D part=<n> and writes a binary STL of a box n mm square. A part
# named "empty" gets a valid STL with no triangles, which is what OpenSCAD
# really does when the model's dispatch matches nothing. A part named
# "broken" gets an ERROR on stderr and no file.
FAKE_OPENSCAD = r'''
import re, struct, sys
args = sys.argv[1:]
out = args[args.index("-o") + 1]
define = ""
if "-D" in args:
    define = args[args.index("-D") + 1].split("=", 1)[1].strip('"')
if define == "broken":
    sys.stderr.write("ERROR: Assertion failed\n")
    sys.exit(1)
size = 40.0
m = re.match(r"^-?[\d.]+$", define or "")
if m:
    size = float(define)
elif define == "huge":
    size = 400.0
tris = []
if define != "empty":
    a, b = (0.0, 0.0, 0.0), (size, 0.0, 0.0)
    c, d = (size, size, 0.0), (0.0, size, 0.0)
    top = (0.0, 0.0, 10.0)
    tris = [(a, b, c), (a, c, d), (a, b, top), (b, c, top)]
with open(out, "wb") as fh:
    fh.write(b"\0" * 80 + struct.pack("<I", len(tris)))
    for t in tris:
        fh.write(struct.pack("<3f", 0.0, 0.0, 1.0))
        for v in t:
            fh.write(struct.pack("<3f", *v))
        fh.write(b"\0\0")
print("Top level object is a 3D object:")
'''

# Orca-shaped help, and a .gcode.3mf whose G-code has a real object marker
# and extruding moves. SLICER_OFFSET shifts those moves off the bed so the
# fit check has something to catch.
FAKE_SLICER = r'''
import json, os, pathlib, sys, zipfile
a = sys.argv[1:]
if "--help" in a:
    print("--slice arg --load-settings arg --load-filaments arg "
          "--export-3mf arg --arrange arg --orient arg --ensure-on-bed "
          "--allow-newer-file --min-save")
    sys.exit(0)
if "--slice" not in a:
    sys.stderr.write("unknown invocation\n"); sys.exit(2)
off = float(os.environ.get("SLICER_OFFSET", "0"))
if os.environ.get("SLICER_FAIL"):
    sys.stderr.write("ERROR: slicing failed\n"); sys.exit(1)
out = a[a.index("--export-3mf") + 1]
pathlib.Path(out).parent.mkdir(parents=True, exist_ok=True)
lines = ["; generated by fake", "; layer_height = 0.2", "G28", "M83",
         "; printing object part id:0 copy 0"]
for x, y in ((20, 20), (60, 20), (60, 60), (20, 60), (20, 20)):
    lines.append("G1 X%.1f Y%.1f Z0.2 E0.5" % (x + off, y + off))
with zipfile.ZipFile(out, "w") as z:
    z.writestr("Metadata/plate_1.gcode", "\n".join(lines) + "\n")
    z.writestr("Metadata/slice_info.config",
               '<?xml version="1.0"?><config><plate>'
               '<metadata key="index" value="1"/>'
               '<metadata key="prediction" value="7412"/>'
               '<filament id="1" type="PLA" used_m="9.94" used_g="29.8"/>'
               '</plate></config>')
    z.writestr("Metadata/project_settings.config",
               json.dumps({"printer_model": "Fake", "layer_height": "0.2"}))
print("slicing finished")
'''


@pytest.fixture
def rig(tmp_path, monkeypatch):
    """A workspace, a fake OpenSCAD, a fake slicer, and a machine record
    fingerprinted over real profile files so staleness() is satisfied."""
    ws = tmp_path / "cad"
    ws.mkdir()
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()

    def script(name, body):
        p = bin_dir / name
        p.write_text("#!" + sys.executable + "\n" + body)
        p.chmod(0o755)
        return p

    openscad = script("openscad", FAKE_OPENSCAD)
    slicer = script("slicer", FAKE_SLICER)

    prof = tmp_path / "profiles"
    prof.mkdir()
    (prof / "machine.json").write_text(json.dumps({
        "type": "machine", "name": "Fake 0.4 nozzle",
        "printable_area": ["0x0", "220x0", "220x220", "0x220"],
        "printable_height": "250", "nozzle_diameter": ["0.4"]}))
    (prof / "process.json").write_text(json.dumps(
        {"type": "process", "name": "0.20mm", "layer_height": "0.2"}))
    (prof / "filament.json").write_text(json.dumps(
        {"type": "filament", "name": "PLA", "filament_type": ["PLA"]}))
    profiles = {"machine": str(prof / "machine.json"),
                "process": str(prof / "process.json"),
                "filament": str(prof / "filament.json")}

    monkeypatch.setenv("CADLOOP_MACHINE", str(tmp_path / "machine.json"))
    monkeypatch.setenv("OPENSCAD_BIN", str(openscad))
    monkeypatch.setenv("SLICER_BIN", str(slicer))
    monkeypatch.delenv("SLICER_OFFSET", raising=False)
    monkeypatch.delenv("SLICER_FAIL", raising=False)
    machine.save({
        "schema": machine.SCHEMA, "name": "Fake 0.4 nozzle",
        "slicer": {"family": "fake", "binary": str(slicer), "version": "1.0"},
        "profiles": profiles,
        "derived": {"printer_model": "Fake", "nozzle_mm": 0.4,
                    "filament_type": "PLA",
                    "bed": {"x_mm": 220.0, "y_mm": 220.0, "z_mm": 250.0,
                            "origin": [0.0, 0.0]}},
        "fingerprint": machine.fingerprint(str(slicer), "1.0", profiles)})

    (ws / "m.scad").write_text('part = "all";\ncube(10);\n')
    return ws


def test_a_whole_run_renders_packs_slices_and_proves_the_bed(rig):
    r = pipeline.run("m.scad", rig, ["30", "40"])
    assert r["ok"] is True, r["reason"]
    assert [p["name"] for p in r["parts"]] == ["30", "40"]
    assert all(p["rendered"] and p["fits"] for p in r["parts"])
    assert r["parts"][0]["size_mm"][:2] == [30.0, 30.0]
    assert len(r["plates"]) == 1
    assert r["plates"][0]["on_bed"] is True
    assert r["totals"] == {"plates": 1, "minutes": 124, "filament_m": 9.94}
    # The G-code and the archive are really on disk, under the workspace.
    plate = Path(r["output"]) / "plate_1.gcode"
    assert plate.is_file() and plate.stat().st_size
    assert zipfile.is_zipfile(Path(r["output"]) / "plate_1.gcode.3mf")
    json.loads(json.dumps(r))


def test_no_parts_argument_renders_the_whole_file(rig):
    r = pipeline.run("m.scad", rig)
    assert r["ok"] is True, r["reason"]
    assert [p["name"] for p in r["parts"]] == ["m"]
    assert (Path(r["output"]) / "m.stl").is_file()


def test_a_plate_off_the_bed_fails_the_run(rig, monkeypatch):
    monkeypatch.setenv("SLICER_OFFSET", "200")
    r = pipeline.run("m.scad", rig, ["30"])
    assert r["ok"] is False
    assert "off the bed" in r["reason"]
    assert r["plates"][0]["on_bed"] is False
    assert any("off the bed" in note for note in r["attention"])


def test_a_part_too_big_for_the_bed_is_reported_not_squeezed(rig):
    r = pipeline.run("m.scad", rig, ["huge", "30"])
    assert r["ok"] is False
    assert "does not fit this bed" in r["reason"]
    big = [p for p in r["parts"] if p["name"] == "huge"][0]
    assert big["rendered"] is True and big["fits"] is False
    assert big["plate"] is None
    assert any("huge does not fit" in note for note in r["attention"])
    # and the part that does fit still got sliced
    assert len(r["plates"]) == 1
    assert r["plates"][0]["parts"] == ["30"]


def test_a_part_that_renders_nothing_is_named(rig):
    r = pipeline.run("m.scad", rig, ["empty", "30"])
    assert r["ok"] is False
    assert "empty did not render" in r["reason"]
    assert any("no geometry" in note for note in r["attention"])
    assert r["plates"][0]["parts"] == ["30"]


def test_an_openscad_error_is_a_failure_not_a_crash(rig):
    r = pipeline.run("m.scad", rig, ["broken"])
    assert r["ok"] is False
    assert "broken did not render" in r["reason"]
    assert r["plates"] == []


def test_a_failed_slice_is_a_failure(rig, monkeypatch):
    monkeypatch.setenv("SLICER_FAIL", "1")
    r = pipeline.run("m.scad", rig, ["30"])
    assert r["ok"] is False
    assert "did not slice" in r["reason"]
    assert r["plates"][0]["sliced"] is False
    assert r["plates"][0]["on_bed"] is None


def test_parts_are_packed_onto_as_few_plates_as_fit(rig):
    r = pipeline.run("m.scad", rig, ["100", "100", "100", "100", "100"])
    # Duplicate names render once, and say so.
    assert len(r["parts"]) == 1
    assert any("more than once" in note for note in r["attention"])
    r = pipeline.run("m.scad", rig, ["90", "91", "92", "93", "94"])
    assert r["ok"] is True, r["reason"]
    # 204 mm of usable bed: two per shelf, two shelves, so one plate holds
    # four and the fifth opens a second.
    assert len(r["plates"]) == 2
    assert sum(len(p["parts"]) for p in r["plates"]) == 5
    assert r["totals"]["plates"] == 2


def test_a_part_that_only_fits_turned_is_reported_as_turned(rig, monkeypatch):
    # 120 x 280 mm on a 300 x 150 bed: too deep square, fine on its side.
    # A square bed can never need a turn, so this one is not square, and the
    # fake OpenSCAD only makes squares, so widen the mesh after it renders.
    monkeypatch.setattr(pipeline, "_bed", lambda rec: {
        "x_mm": 300.0, "y_mm": 150.0, "z_mm": 250.0, "origin": [0.0, 0.0]})
    real_render = pipeline._render

    def oblong(binary, source, outdir, workspace, name, define):
        rec = real_render(binary, source, outdir, workspace, name, define)
        if name == "oblong":
            rec["size_mm"] = [120.0, 280.0, 10.0]
        return rec

    monkeypatch.setattr(pipeline, "_render", oblong)
    r = pipeline.run("m.scad", rig, ["oblong"])
    assert r["ok"] is True, r["reason"]
    assert r["arranged"] == ["oblong turned 90 degrees, it does not fit square"]


def test_a_plate_near_the_edge_suggests_a_brim(rig, monkeypatch):
    monkeypatch.setenv("SLICER_OFFSET", "-15")
    r = pipeline.run("m.scad", rig, ["30"])
    assert r["ok"] is True, r["reason"]
    assert any("consider a brim" in note for note in r["attention"])


def test_unreadable_gcode_is_unknown_not_a_failure(rig, monkeypatch):
    def blank(path, bed, margin_mm=0.0):
        return {"ok": None, "reason": "no object marker in this G-code",
                "extent": {}, "bed": bed}

    monkeypatch.setattr(pipeline._gcode, "fits", blank)
    r = pipeline.run("m.scad", rig, ["30"])
    assert r["ok"] is None
    assert "could not be read" in r["reason"]
    assert r["plates"][0]["on_bed"] is None


def test_a_slicer_refusal_stops_the_run(rig, monkeypatch):
    monkeypatch.setattr(slicer_server, "slice_model",
                        lambda **kw: {"ok": None, "reason": "no printer set "
                                                            "up, run setup_printer"})
    r = pipeline.run("m.scad", rig, ["30"])
    assert r["ok"] is None
    assert "setup_printer" in r["reason"]
    assert r["plates"] == []


def test_a_bed_with_no_geometry_refuses_before_rendering(rig, monkeypatch):
    monkeypatch.setattr(pipeline, "_bed", lambda rec: {})
    r = pipeline.run("m.scad", rig, ["30"])
    assert r["ok"] is None
    assert "printable area" in r["reason"]
    assert r["parts"] == [] and not (rig / "plates").exists()


def test_an_empty_parts_list_refuses(rig):
    r = pipeline.run("m.scad", rig, [])
    assert r["ok"] is None
    assert "nothing to render" in r["reason"]


def test_a_missing_source_refuses(rig):
    r = pipeline.run("gone.scad", rig)
    assert r["ok"] is None
    assert "gone.scad" in r["reason"]


def test_a_numeric_part_is_passed_to_openscad_as_a_number(rig, monkeypatch):
    seen = []
    real = pipeline._sh
    monkeypatch.setattr(pipeline, "_sh",
                        lambda cmd, t: (seen.append(cmd), real(cmd, t))[1])
    pipeline.run("m.scad", rig, ["36", "ring"])
    defines = [c[c.index("-D") + 1] for c in seen if "-D" in c]
    assert defines == ["part=36", 'part="ring"']


def test_the_run_leaves_the_slicer_workspace_where_it_found_it(rig):
    was = slicer_server.WORKSPACE
    pipeline.run("m.scad", rig, ["30"])
    assert slicer_server.WORKSPACE == was
