from pathlib import Path

import pytest

from cadloop import gcode

# The shape a real Creality start macro has: a prime line that extrudes at
# negative X on purpose, then the object, then a present-print move to the
# far edge of the bed. Only the middle section is the part.
SAMPLE = """; HEADER_BLOCK_START
; layer_height = 0.2
; printer_model = Creality Ender-3 V3 SE
G28 ;Home
G92 E0
G1 X-2.1 Y20 Z0.28 F5000.0 ;Move to start position
G1 X-2.1 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line
G1 X-2.4 Y145.0 Z0.28 F5000.0 ;Move to side a little
G1 X-2.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line
G92 E0
M83
; printing object part.stl id:0 copy 0
G1 X30 Y30 F9000
G1 Z0.2
G1 X60 Y30 E.4
G1 X60 Y70 E.4
G1 X30 Y70 E.4
G1 X30 Y30 E.4
G1 E-1.2 F2400
G1 X0 Y220 ;Present print
M104 S0 ;Turn-off hotend
"""


@pytest.fixture
def sample(tmp_path):
    p = tmp_path / "part.gcode"
    p.write_text(SAMPLE)
    return p


def test_extent_ignores_the_prime_line(sample):
    e = gcode.extent(sample)
    assert e["x"][0] == 30.0, "the prime line at X-2.4 is not part of the part"


def test_extent_ignores_the_present_print_move(sample):
    e = gcode.extent(sample)
    assert e["y"][1] == 70.0, "the end macro's move to Y220 is not the part"


def test_extent_counts_only_extruding_moves(sample):
    e = gcode.extent(sample)
    assert e["moves"] == 4


def test_extent_reports_z(sample):
    assert gcode.extent(sample)["z_max"] == 0.2


def test_extent_of_a_file_with_no_object_marker_is_unknown(tmp_path):
    p = tmp_path / "empty.gcode"
    p.write_text("G28 ;Home\nG1 X10 Y10 E1\n")
    e = gcode.extent(p)
    assert e["ok"] is None
    assert "reason" in e


def test_header_reads_the_semicolon_block(sample):
    h = gcode.header(sample)
    assert h["layer_height"] == "0.2"
    assert h["printer_model"] == "Creality Ender-3 V3 SE"


def test_fits_passes_a_part_inside_the_bed(sample):
    r = gcode.fits(sample, {"x_mm": 220.0, "y_mm": 220.0, "z_mm": 250.0})
    assert r["ok"] is True


def test_fits_fails_a_part_over_the_edge(sample):
    r = gcode.fits(sample, {"x_mm": 50.0, "y_mm": 50.0, "z_mm": 250.0})
    assert r["ok"] is False
    assert "60.0" in r["reason"]


def test_fits_is_unknown_without_a_bed(sample):
    r = gcode.fits(sample, {})
    assert r["ok"] is None
    assert "bed" in r["reason"]


# Real OrcaSlicer output: the HEADER_BLOCK at the top uses colon syntax and
# holds only the generator banner and a couple of fields, a decoy
# "; ... width = ..." block sits below it using unrelated key names, and the
# authoritative full `key = value` config block is written at the very end
# of the file, after all the G-code. header() must read to the end and let
# the tail win, not stop at the first non-comment line it meets.
TAIL_METADATA_SAMPLE = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2
; HEADER_BLOCK_END

; external perimeters extrusion width = 0.42mm

G28 ;Home
M83
; printing object part.stl id:0 copy 0
G1 X10 Y10 E1
M104 S0 ;Turn-off hotend

; layer_height = 0.2
; printer_model = Creality Ender-3 V3 SE
"""


def test_header_reads_the_trailing_metadata_block_not_the_leading_decoy(tmp_path):
    p = tmp_path / "tail.gcode"
    p.write_text(TAIL_METADATA_SAMPLE)
    h = gcode.header(p)
    assert h["layer_height"] == "0.2"
    assert h["printer_model"] == "Creality Ender-3 V3 SE"


# Real OrcaSlicer HEADER_BLOCK uses colon syntax, and that is the only place
# max_z_height is ever written.
COLON_HEADER_SAMPLE = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2 on 2026-07-28 at 19:41:51
; max_z_height: 7.00
; HEADER_BLOCK_END

; printing object part.stl id:0 copy 0
G1 X10 Y10 E1
"""


def test_header_reads_colon_syntax_inside_the_header_block(tmp_path):
    p = tmp_path / "colon.gcode"
    p.write_text(COLON_HEADER_SAMPLE)
    h = gcode.header(p)
    assert h["max_z_height"] == "7.00"


# Under absolute extrusion (M82) a retraction is a *positive* E lower than
# the running total, not a negative one.
ABSOLUTE_RETRACT_SAMPLE = """; printing object part.stl id:0 copy 0
M82
G92 E0
G1 X10 Y10 E5
G1 X20 Y10 E10
G1 X20 Y20 E8
"""


def test_extent_ignores_an_absolute_mode_retraction(tmp_path):
    p = tmp_path / "absolute.gcode"
    p.write_text(ABSOLUTE_RETRACT_SAMPLE)
    e = gcode.extent(p)
    assert e["moves"] == 2
    assert e["y"][1] == 10.0, "the E8 move is a retraction (8 < 10), not a print move"


# A travel line whose trailing comment happens to mention a positive E
# value must not be mistaken for an extruding move: the comment is not code.
TRAVEL_COMMENT_SAMPLE = """; printing object part.stl id:0 copy 0
M83
G1 X10 Y10 E1
G1 X200 Y200 F9000 ;travel to next object E5, not a real extrusion
"""


def test_extent_ignores_e_text_inside_a_comment(tmp_path):
    p = tmp_path / "travelcomment.gcode"
    p.write_text(TRAVEL_COMMENT_SAMPLE)
    e = gcode.extent(p)
    assert e["moves"] == 1
    assert e["x"][1] == 10.0, "the travel move's comment mentions E but the move itself does not extrude"


# A zero-length extrusion lays no plastic and must not extend the extent.
ZERO_E_SAMPLE = """; printing object part.stl id:0 copy 0
M83
G1 X10 Y10 E1
G1 X50 Y50 E0
"""


def test_extent_ignores_a_zero_length_extrusion(tmp_path):
    p = tmp_path / "zeroe.gcode"
    p.write_text(ZERO_E_SAMPLE)
    e = gcode.extent(p)
    assert e["moves"] == 1
    assert e["x"][1] == 10.0, "E0 extrudes nothing so it should not extend the extent"
