#!/usr/bin/env python3
import sys, zipfile, json, pathlib
a = sys.argv[1:]
if "--help" in a or "-h" in a:
    print("""CrealityPrint-7.1.0 (Orca fork)
Usage: CrealityPrint [ OPTIONS ] [ file.3mf/file.stl ... ]
  --slice arg  --load-settings arg  --load-filaments arg  --export-3mf arg
  --outputdir arg  --arrange arg  --orient arg  --ensure-on-bed
  --allow-newer-file  --min-save  --no-check  --debug arg  --info
  --layer-height arg  --sparse-infill-density arg""")
    sys.exit(0)
if "--info" in a:
    print("Object: 1 volumes, size 167.75 x 167.75 x 7.00"); sys.exit(0)
if "--slice" in a:
    out = a[a.index("--export-3mf")+1]
    pathlib.Path(out).parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w") as z:
        z.writestr("Metadata/plate_1.gcode",
                   "; generated by mock\n; layer_height = 0.2\nG28\nG1 X10 Y10\n")
        z.writestr("Metadata/slice_info.config",
                   '<?xml version="1.0"?><config>'
                   '<header><header_item key="X-Slicer" value="CrealityPrint"/></header>'
                   '<plate><metadata key="index" value="1"/>'
                   '<metadata key="prediction" value="7412"/>'
                   '<metadata key="weight" value="29.8"/>'
                   '<filament id="1" type="PLA" color="#1F8A70" used_m="9.94" used_g="29.8"/>'
                   '</plate></config>')
        z.writestr("Metadata/project_settings.config", json.dumps({
            "printer_model": "Creality K1", "layer_height": "0.2",
            "sparse_infill_density": "15%", "nozzle_diameter": ["0.4"],
            "filament_type": ["PLA"], "print_settings_id": "0.20mm Standard"}))
    print("slicing finished"); sys.exit(0)
sys.stderr.write("unknown invocation\n"); sys.exit(2)
